pub mod api;
//mod as_html;
pub mod builder;
pub mod bulk;
pub mod connections_controller;
pub mod data_reader_controller;
pub mod debug_controller;
pub mod gc_controller;
//pub mod home_controller;
mod mappers;
pub mod persist_controller;

//pub mod logs_controller;
pub mod multipart;
pub mod namespaces_controller;
pub mod prometheus_controller;
pub mod row_controller;
pub mod rows_controller;
pub mod status_controller;
pub mod tables_controller;
pub mod transactions;
pub mod ui_settings_controller;
pub use mappers::*;
pub mod backup;
pub mod partitions;
